### ISSUE TITLE
Missing libmtx.so

### ISSUE THREAD

**Issue by keeperAndy** [Enstore-org/enstore#48]
../modules/Setup tries to link to a `libmtx.so` library by assuming it is included with an installed `mtx` package. The command substitution in question is on line 84:

    MTX_LIB=`rpm -ql mtx | grep libmtx.so`

The `mtx` package in the public SL7 repos at least no longer include any libraries, and there do not seem to be any mtx-devel or libmtx packages available that provide a `libmtx.so` library either. 

```
# repoquery -ql mtx
/usr/sbin/loaderinfo
/usr/sbin/mtx
/usr/sbin/scsieject
/usr/sbin/scsitape
/usr/sbin/tapeinfo
/usr/share/doc/mtx-1.3.12
/usr/share/doc/mtx-1.3.12/CHANGES
/usr/share/doc/mtx-1.3.12/COMPATABILITY
/usr/share/doc/mtx-1.3.12/FAQ
/usr/share/doc/mtx-1.3.12/LICENSE
/usr/share/doc/mtx-1.3.12/README
/usr/share/doc/mtx-1.3.12/TODO
/usr/share/doc/mtx-1.3.12/contrib
/usr/share/doc/mtx-1.3.12/contrib/MTX.html
/usr/share/doc/mtx-1.3.12/contrib/README
/usr/share/doc/mtx-1.3.12/contrib/TapeChanger-MTX-0.71b.tar.gz
/usr/share/doc/mtx-1.3.12/contrib/config_sgen_solaris.sh
/usr/share/doc/mtx-1.3.12/contrib/mtx-changer
/usr/share/doc/mtx-1.3.12/contrib/mtx.py
/usr/share/doc/mtx-1.3.12/contrib/mtxctl-0.0.2.tar.gz
/usr/share/doc/mtx-1.3.12/contrib/qdback.tar.gz
/usr/share/doc/mtx-1.3.12/contrib/tapechanger.html
/usr/share/doc/mtx-1.3.12/contrib/tapeinfo.py
/usr/share/doc/mtx-1.3.12/contrib/tapeload.pl
/usr/share/doc/mtx-1.3.12/contrib/tapeunload.pl
/usr/share/doc/mtx-1.3.12/mtx.doc
/usr/share/doc/mtx-1.3.12/mtxl.README.html
/usr/share/man/man1/loaderinfo.1.gz
/usr/share/man/man1/mtx.1.gz
/usr/share/man/man1/scsieject.1.gz
/usr/share/man/man1/scsitape.1.gz
/usr/share/man/man1/tapeinfo.1.gz
```

      # yum provides "*/*libmtx*"
         No matches found

This missing library causes `make` to fail for some targets in ../modules/ and leaves Enstore missing compiled components it seems to need for the `media_changer` service to function with the `MTXN_MediaLoader` class.

**Comment by renbauer-fnal** [comment]
Hey Andy,

This version of the libmtx library is included in a modified version of the mtx rpm in use here at Fermilab. We've forked the source for this library to a new repo at https://github.com/Enstore-org/mtx, as well as uploaded our rpm as a release under that repo at https://github.com/Enstore-org/mtx/releases/tag/mtx-1.3.12-18fnal.

We've also updated our build image to include this mtx library, although I don't believe the code is actually packaged into the Enstore rpm, so I don't think that will resolve the issue you're seeing. As it is a "soft" dependency (personal feelings on whether or not such a thing exists notwithstanding), we don't list the package as required in our rpm spec.

Note Enstore indeed requires a modified version of the Python (2.7.16) interpreter as well, which *is* included in the Enstore rpm. However, this Python environment needs to be configured using something like this setup-enstore file: https://github.com/Enstore-org/enstore/blob/develop/.github/docker/cc7-enstore/data/setup-enstore.

We're aware this is generally unintuitive, and are working on improvements, but will note Enstore at Fermilab is intended to reach EOL soon in favor of Cern Tape Archive (CTA), which you can learn more about at https://cta.web.cern.ch/cta/.

Happy to hear more about your use case if there's more we can help with - Ren

**Comment by keeperAndy** [comment]
Thank you, the FNAL version of mtx being present did the trick. In our case I built it, placed it by hand, and updates the Setup files to point to library rather than depend on an rpm query to locate it.

**Comment by renbauer-fnal** [comment]
Glad to hear it - Ren
